linters:
  disable:
    - gofumpt
    - tagalign
linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - "!**/*.go"
        allow:
          - $gostd
          - github.com/MaUhlik-cen56998/go-index